name: Azure Bicep Deployment

on:
  workflow_dispatch:  # Allows manually triggering the workflow

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  LOCATION: swedencentral  # Default location for resources

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Ensure the Resource Group exists (create if it doesn't exist)
    - name: Ensure Resource Group exists
      run: |
        az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ env.LOCATION }} \
        --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 4: Deploy the Bicep template (idempotent deployment)
    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --template-file './main.bicep' \
          --parameters @./path/to/parameters.json \
          --mode Incremental