name: Lab application build

on: 
  push:
    branches:
      - main
    paths:
      - lab1/**  # Triggers the workflow when any file in the lab3 folder is changed
 
env:
  DOCKERHUB_USERNAME: danielfroding
  DOCKER_IMAGE_NAME: scalingcloud
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run setup script
      run: |
        cd lab1
        chmod +x setup-massively.sh    # Ensure the script is executable
        ./setup-massively.sh           # Execute the script

    - name: Log in to Docker Hub
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  
    # Step 3: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest ./lab1
        docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest
