name: Lab Bicep Deployment

on: 
  workflow_dispatch:
    inputs:
      labPath:
        description: 'Lab nr (Directory where the bicepfile for the lab is located)'
        required: true
        default: 'lab3'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}/${{ github.event.inputs.labPath }}
  LOCATION: swedencentral  # Default location for resources

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Ensure the Resource Group exists (create if it doesn't exist)
    - name: Create Resource Group for ${{ github.event.inputs.labPath }}
      run: |
        az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }} \
        --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Bicep file for ${{ github.event.inputs.labPath }}
      run: |
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --template-file ${{ github.event.inputs.labPath }} + '/lab.bicep' \
          --mode Incremental