name: Lab3 Bicep Deployment

on:
  workflow_dispatch:  # Allows manually triggering the workflow
  push:
    branches:
      - main
    paths:
      - lab1/**  # Triggers the workflow when any file in the lab3 folder is changed
      - lab3/**  # Triggers the workflow when any file in the lab3 folder is changed

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  LOCATION: swedencentral  # Default location for resources
  DOCKERHUB_USERNAME: danielfroding
  DOCKER_IMAGE_NAME: scalingcloud
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run setup script
      run: |
        cd lab1
        chmod +x ./setup-massively.sh  # Ensure the script is executable
        ./setup-massively.sh           # Execute the script
        cd ..

        - name: Log in to Docker Hub
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  
    # Step 3: Build and Push Docker Image
    - name: Build and push Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest ./lab1
        docker push $DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Ensure the Resource Group exists (create if it doesn't exist)
    - name: Ensure Resource Group exists
      run: |
        az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ env.LOCATION }} \
        --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Step 4: Deploy the Bicep template (idempotent deployment)
    - name: Deploy Bicep template
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --template-file './lab3/application.bicep' \
          --mode Incremental