name: Delete Azure Resource Group

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  delete-resource-group:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Log in to Azure using the stored credentials
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # The Azure service principal JSON

    # Step 2: Delete the Resource Group using Azure CLI
    - name: Delete Resource Group
      run: |
        # Get all resource groups with the tag 'Project: Lab' and delete them
        az group list --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --tag Project=scalingCloudLab --query "[].name" -o tsv | xargs -I {} az group delete --name {} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --yes --no-wait